variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

stages:
  - build
  - deploy

build:
    stage: build
    script:
    - bundle exec jekyll build -d public
    tags: 
    - jekyll

deploy:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - rm -rf /var/www/vhosts/outadoc.fr/htdocs/*
  - cp -R public/* /var/www/vhosts/outadoc.fr/htdocs/
  tags: 
  - jekyll
  only:
  - master
