tags: jekyll

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install
  

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  except:
  - master

deploy:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - cp -R _site /var/www/vhosts/outadoc.fr/htdocs/
  artifacts:
    paths:
    - public
  only:
  - master
